name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution / API
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
