name: CI
on:
  pull_request:
  push:
    branches: [master, main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest markdownlint-cli
      - name: Lint Python with black
        run: black --check .
      - name: Lint Python with flake8
        run: flake8 .
      - name: Lint Markdown
        run: npx markdownlint '**/*.md'
      - name: Run tests
        run: pytest
